from backend.db.supabase_client import supabase

# Your SPAC tickers + company names
SPAC_TICKERS = [
    ("YDES", "YD Bio Limited"),
    ("KYIV", "Kyivstar Group Ltd."),
    ("BBOT", "BridgeBio Oncology"),
    ("PLBL", "Polibeli Group Ltd."),
    ("PEW", "GrabAGun Digital Holdings"),
    ("VWAV", "VisionWave Technologies"),
    ("PFSA", "Profusa, Inc."),
    ("YOUL", "Youlife Group Inc."),
    ("HBNB", "Hotel101 Global Holdings"),
    ("SCAG", "Scage Future"),
    ("BGL", "Blue Gold Limited"),
    ("DAIC", "CID HoldCo, Inc."),
    ("SAFX", "XCF Global Capital"),
    ("NAMM", "Namib Minerals"),
    ("TGE", "The Generation Essentials Group"),
    ("KWM", "K Wave Media Ltd."),
    ("GIBO", "GIBO Holdings Limited"),
    ("LIMN", "Liminatus Pharma, Inc."),
    ("BULL", "Webull Corporation"),
    ("MGTE", "Marblegate Capital Co"),
    ("KIDZ", "Classover Holdings, Inc."),
    ("USAR", "USA Rare Earth"),
    ("ASBP", "Aspire Biopharma Holdings, Inc."),
    ("CYCU", "Cycurion, Inc."),
    ("FLD", "Fold Holdings, Inc."),
    ("OSRH", "OSR Holdings, Inc."),
    ("GCL", "GCL Global Holdings Ltd."),
    ("GMHS", "Gamehaus Holdings Inc."),
    ("KBSX", "FST Corp."),
    ("BZAI", "Blaize Holdings, Inc."),
    ("STAI", "ScanTech AI Systems Inc."),
    ("RAIN", "Rain Enhancement Technologies, Inc."),
    ("AMOD", "Alpha Modus Corp."),
    ("ANNA", "AleAnna, Inc."),
    ("CNCK", "Coincheck, Inc."),
    ("NUAI", "New Era Energy & Digital, Inc."),
    ("TNMG", "TNL Mediagene"),
    ("ELPW", "Elong Power Holding Limited"),
    ("RMSG", "Real Messenger Corp."),
    ("ABP", "Abpro Holdings, Inc."),
    ("DEVS", "DevvStream Corp."),
    ("INV", "Innventure, Inc."),
    ("BDMD", "Baird Medical Investment Holdings Limited"),
    ("FOXX", "Foxx Development Holdings Inc."),
    ("SBC", "SBC Medical Group Holdings"),
    ("VEEA", "Veea Inc."),
    ("CURR", "CURRENC Group Inc."),
    ("RZLV", "Rezolve AI PLC"),
    ("SLXN", "Silexion Therapeutics Corp."),
    ("BSLK", "Bolt Projects Holdings"),
    ("CTOR", "Citius Oncology, Inc."),
    ("GGAAF", "NeuroMind AI Corp."),
    ("HPAI", "Helport AI Limited"),
    ("MKDW", "MKDWELL Tech Inc."),
    ("ADGM", "Adagio Medical Holdings, Inc."),
    ("PITEF", "Heramba Electric plc"),
    ("PSIG", "PS International Group Ltd."),
    ("CNTM", "ConnectM Technology Solutions, Inc."),
    ("CGBSF", "Crown LNG Holdings Limited"),
    ("SDST", "Stardust Power Inc."),
    ("TOYO", "TOYO Co., Ltd."),
    ("ABVE", "Above Food Ingredients Inc."),
    ("VSEE", "VSee Health, Inc."),
    ("AIEV", "Thunder Power Holdings, Inc."),
    ("KLTO", "Klotho Neurosciences, Inc."),
    ("DSY", "Big Tree Cloud Holdings Limited"),
    ("LION", "Lionsgate Studios Corp."),
    ("OKLO", "Oklo, Inc."),
    ("NUVOQ", "Nuvo Group Ltd."),
    ("CNXX", "CONX Corp."),
    ("SHMD", "SCHMID Group N.V."),
    ("AILEQ", "iLearningEngines, Inc."),
    ("ZOOZ", "ZOOZ Power"),
    ("NIVF", "NewGenIvf"),
    ("FAAS", "DigiAsia"),
    ("ZPTA", "Zapata Computing"),
    ("MCAF", "CH-Auto"),
    ("LPA", "Logistic Properties of the Americas"),
    ("GCTS", "GCT Semiconductor"),
    ("DJT", "Trump Media & Technology Group"),
    ("COOT", "Australian Oilseeds Investments Pty Ltd."),
    ("MRNO", "Murano Global Investments Plc"),
    ("BCG", "Binah Capital Group"),
    ("AIRJ", "AirJoule Technologies Corp."),
    ("BNAI", "Brand Engagement Network"),
    ("GTI", "Graphjet Technology"),
    ("ZEO", "Zeo Energy"),
    ("NMHI", "Nature’s Miracle"),
    ("QTIH", "QT Imaging Holdings, Inc."),
    ("FUFU", "BitFuFu Inc."),
    ("CRML", "Critical Metals Corp."),
    ("LOT", "Lotus Technology Inc."),
    ("SELX", "Semilux International Ltd."),
    ("SOC", "Sable Offshore Corp."),
    ("TVGN", "Tevogen Bio Holdings Inc."),
    ("CERO", "CERo Therapeutics, Inc."),
    ("ATCH", "AtlasClear, Inc."),
    ("DHAI", "DIH Holding US, Inc."),
    ("BRLS", "Borealis Foods Inc."),
    ("STI", "Solidion Technology Inc."),
    ("TRUG", "TruGolf Holdings, Inc."),
    ("PBM", "Psyence Biomedical Ltd."),
    ("HOVR", "New Horizon Aircraft Ltd."),
    ("HWH", "HWH International Inc.")
]

def seed_spac_list():
    for ticker, company in SPAC_TICKERS:
        supabase.table("spac_list").upsert({
            "ticker": ticker,
            "company_name": company
        }).execute()
    print("✅ Seeded spac_list with", len(SPAC_TICKERS), "tickers")

if __name__ == "__main__":
    seed_spac_list()
